### ISSUE TITLE
How to combine this script with a model generated on https://teachablemachine.withgoogle.com/

### ISSUE THREAD

**Issue by MichielBontenbal** [google-coral/project-teachable#11]
Hi, 

I've installed this and I have also created a model on https://teachablemachine.withgoogle.com/.

How can I combine that model and have it run on my Raspberry Pi?

**Comment by LukasLoacker** [comment]
Please describe what you are trying to achieve in more detail for a specific answer.

In general: If you want to run your model on the Raspberry Pi with coral usb accelerator you need to download the model in the edgeTPU format and than I suggest having a look this [repository](https://github.com/google-coral/examples-camera/tree/master/raspicam).

As this does not seem to be an issue. I think stackoverflow would be a more suitable place for this question.

**Comment by MichielBontenbal** [comment]
Many thanks for a very quick reply. I will look into the other repository, very helpful. 
And you're right of course: it's not an issue - but I did not know where to start. Thanks again.

**Comment by moorka2820** [comment]
I got the same question. Is it possible  to use the  saved   .tflite model   and  labels  from teachable machine  in this scrypt?? 
Any help would be appreciated

**Comment by hjonnala** [comment]
@moorka2820 you can compile .tfltie model with [compiler](https://colab.research.google.com/github/google-coral/tutorials/blob/master/compile_for_edgetpu.ipynb) and use the complied edgeptu tflite model and labels in this [script](https://github.com/google-coral/examples-camera/blob/master/raspicam/classify_capture.py) if it's a classification model.
