### ISSUE TITLE
segmeentation fault

### ISSUE THREAD

**Issue by SEYDINALAYE** [google-coral/project-teachable#14]
Hello, Thank you for this project which is really interesting. I start to do it again but I find the following error "segmentation fault" when I run the code techeable.py.
Could you help me thank you in advance.

**Comment by manoj7410** [comment]
@SEYDINALAYE This repo's issues got missed somehow. Are you still facing this issue ?

**Comment by manoj7410** [comment]
Feel free to reopen if the issue still persists.
