### ISSUE TITLE
converting project to pycoral

### ISSUE THREAD

**Issue by arrow53** [google-coral/project-teachable#18]
has anyone looked at converting this project to the new API? the API has changed quite a bit.

**Comment by hjonnala** [comment]
Please let us know if you are facing issues while converting this project to the new API.

**Comment by arrow53** [comment]
@hjonnala There are quite a few changes and I was hoping to just not repeat work. If I get some time in the future I can fork and take a stab at it. I'm going to just close for now so you don't have a hanging issue.
