### ISSUE TITLE
CLASSIFICATION || Optimize algorithms

### ISSUE THREAD

**Issue by AlexHarrison1** [google-coral/project-teachable#19]
### Description

Hi all,

I am a newer in this area. I am using Pi4+Coral USB for Classification project as Embedded Teachable Machine tutorial. Everything goes well but I'd like to know how we can optimize performance by adding algorithms to eliminate fews unnecessary things . For instance: 

- During the whole process, instead of sending every frame for classifications, I just want to determine and take the best image for a classification (maybe at the center of the frame) and then extract only that result into output to control hardware. Others will be skipped.
- The second one might be about time. Is it possible for us creating a function "DELAY"? For example, we have a specific cycle time and for each cycle, we will show the result of classification. Will the delay be a solution for this issue? 

I am really looking for your suggestion on both coding and algorithm!
Thanks in advance!

<details><summary>Click to expand!</summary> 
 
 ### Issue Type

Performance

### Operating System

Linux

### Coral Device

Dev Board, USB Accelerator

### Other Devices

Rapsberry Pi 4

### Programming Language

Python 3.7

### Relevant Log Output

_No response_</details>

**Comment by hjonnala** [comment]
Hi @AlexHarrison1 sorry, we don't have any suggestion for this issue. May be stack over flow community might be able to best answer this question.

Good Luck!
