### ISSUE TITLE
How to use USB camera

### ISSUE THREAD

**Issue by rouyunpan** [google-coral/project-teachable#3]
I don't buy Coral Camera.
I use my USB camera with coral dev board.

How to modify the code to use usb camera ?

**Comment by LukasLoacker** [comment]
Did you try it? Take a look at gstreamer.py file. The script checks which source is available. If you need further instructions check out [coral docs ](https://coral.withgoogle.com/docs/dev-board/camera/) on how to set up a usb camera. 

As this is not an issue with the code itself, you should probalbly ask this question on stackoverflow.

**Comment by rouyunpan** [comment]
In gstreamer.py , there is hard code, my USB camera can't work for this project. 
My camera is OK for other demo.

I already the coral docs, It mentions It can work on coral board with the camera. 
Only for Coral camera?  I want to confirm this.

I should can select /dev/video1 or /dev/video1.  on Coral dev board , 

---------------------------------------------------------------------------------------------------
if detectCoralDevBoard():
        SRC_CAPS = 'video/x-raw,format=YUY2,width={width},height={height},framerate=30/1'
        PIPELINE += """
            t. ! {leaky_q} ! glupload ! glfilterbin filter=glcolorscale
               ! {dl_caps} ! videoconvert ! {sink_caps} ! {sink_element}
            t. ! {leaky_q} ! glupload ! glfilterbin filter=glcolorscale
               ! rsvgoverlay name=overlay ! waylandsink
        """
------------------------------------------------------------------

Thank/

**Comment by rouyunpan** [comment]
FYI

I modify this code section in gstreamer.py. My USB camera can work now. 
from 
PIPELINE = 'v4l2src ! {src_caps} ! {leaky_q}  ! tee name=t'
to  
PIPELINE = 'v4l2src device=/dev/video1 ! {src_caps} ! {leaky_q}  ! tee name=t'
