### ISSUE TITLE
raspberry pi 4 version?

### ISSUE THREAD

**Issue by msbrown** [google-coral/project-teachable#4]
Any idea when a version of the edgetpu_api file will be ready for pi 4? I get a null when running install.sh because the current version doesn't list Pi 4 yet. Any advice in meantime?

**Comment by mtyka** [comment]
Rpi4 support is on the way. In the meantime, check out 
https://github.com/leswright1977/RPi4-Google-Coral
and
https://blog.hackster.io/benchmarking-machine-learning-on-the-new-raspberry-pi-4-model-b-88db9304ce4

for workarounds

**Comment by mtyka** [comment]
Alright, to make things easy for everyone I just uploaded a prebuilt image for Rpi4+Buster that includes a bunch of examples and models as well. 
 https://github.com/google-coral/edgetpu-platforms
