### ISSUE TITLE
sh install_requirements.sh Not working

### ISSUE THREAD

**Issue by ChristianEmeis** [google-coral/project-teachable#8]
I own the Coral Dev Board, and everytime I type in "sh install_requirements.sh", it outputs me this error message: "sh: 0: Can't open install_requirements.sh" . In the Instructions here on GitHub it says that I dont need to install anything extra, but now Im not sure If Im missing something. I hope somebody can help me!

**Comment by LukasLoacker** [comment]
Try to use `bash install_requirements.sh`. As the script starts with `#!/bin/bash` you need to use `bash` instead of `sh`.

For a more detailed explination please follow [this answer](https://stackoverflow.com/questions/5725296/difference-between-sh-and-bash#5725402) on stackoverflow.

**Comment by ChristianEmeis** [comment]
If I type in `bash install_requirements.sh`  , the output is `bash: install_requirements.sh: No such file or directory` In the Tutorial here on GitHub its the first Step, but Im not sure if Im missing something. Hopefully somebody can help me out, and Thanks for your Help!

**Comment by LukasLoacker** [comment]
What are the respective commands to reproduce the error?

The following commands should enable a smoothly installation:
`git clone https://github.com/google-coral/project-teachable.git`
`cd project-teachable/`
`bash install_requirements.sh`

**Comment by ChristianEmeis** [comment]
Thank you, that fixed my problem. But before I had to install git by typing in `sudo apt-get install git-all`. Thanks for your help!
